apiVersion: v1
kind: Service
metadata:
  name: github-app-service
  labels:
    app: github-app
spec:
  selector:
      app: github-app
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  type: ClusterIP