apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../infrastructure/application/github-service
  - ../../infrastructure/application/auth-service
patchesStrategicMerge:
  - ./labels.yaml
  - ./env_vars.yaml
  - ./service.yaml
patchesJson6902:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: auth-app-v2
    target:
      kind: Deployment
      name: auth-app
  - patch: |-
      - op: replace
        path: /metadata/name
        value: github-app-v2
    target:
      kind: Deployment
      name: github-app
  - patch: |-
      - op: replace
        path: /metadata/name
        value: github-app-service-v2
    target:
      kind: Service
      name: github-app-service
