apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-app
  labels:
    app: github-app
spec:
  replicas: {{ .Values.githubApp.deployment.replicas }}
  selector:
    matchLabels:
      app: github-app
  template:
    metadata:
      annotations:
        prometheus.io/port: "8088"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: github-app
    spec:
      containers:
        - name: github-app
          image: {{.Values.dockerhub.username}}/{{.Values.githubApp.image.name}}:{{ .Values.githubApp.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.githubApp.http.port}}
